### ISSUE TITLE
Fix Layout and PartialId cleanup

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/launcher-include#10]
@tomalec discovered that my code in https://github.com/StarcounterPrefabs/launcher-include/commit/d4f22311d6932fa3284e4090f3e26e65838192c3 does not properly reset j-t-l when the partial is removed.

**Comment by warpech** [comment]
@tomalec I have made a fix, but now the tests don't pass in Firefox. This might be some problem in `j-t-t`. Could you please take a look?

**Comment by miyconst** [comment]
I will take a look if this issue is not solved before I have some time released.

**Comment by tomalec** [comment]
Done.

You was expecting `juicy-tile-grid.setup` to be `null. What will not happen.
Setting it to `null`, will remove the attribute (set it to null), and reset setup property to default setup.
