### ISSUE TITLE
Pull recent changes from Launcher, release a version 0.6

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/launcher-include#14]
Pull recent changes from Launcher (
https://github.com/StarcounterPrefabs/Launcher/blob/983034a8b7712b70a9aa3df0fa90f40467b1d437/src/Launcher/wwwroot/sys/starcounter-include/starcounter-include.html)

After this is done, release `launcher-include` 0.6, and install this version in Launcher using bower.

**Comment by aloscha** [comment]
Pushed changes and released new version.
