### ISSUE TITLE
Merge with starcounter-include

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/launcher-include#20]
After next Starcounter stable is released, merge this repository into one and only starcounter-include.

Move issues as well.

Then this repo can be removed.

**Comment by tomalec** [comment]
Unfortunately, ZenHub does not support moving between different organizations. I have moved manually opened issue, and on closed, that might be refereed in future.

I've released a new version of `launcher-include` with no code, just `console.warn` with message:
> You are using an old source of `launcher-include`! It is now supported and maintained as `starcounter-include` at https://github.com/Starcounter/starcounter-include/. Please, update your dependencies.

I have also updated release notes for both repos.
