### ISSUE TITLE
Move to a different organisation

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/launcher-include#5]
`launcher-include` is not a sample app but it is currently in [StarcounterSamples](https://github.com/StarcounterSamples) organisation.

It should be moved to another organisation. I propose to move it to [Starcoutner](https://github.com/Starcounter) (which is where `starcounter-include` needs to be as well)

Alternatively, let's merge it to [Launcher](https://github.com/StarcounterSamples/Launcher) but then we will lose the possibility to pull changes from [`starcounter-include`](https://github.com/StarcounterSamples/starcounter-include). Did we use this possibility so far?

Related: https://github.com/StarcounterSamples/starcounter-include/issues/6

@tomalec @miyconst WDYT?

**Comment by miyconst** [comment]
I think we should either merge it with Launcher or keep it in same organization where Launcher is.

**Comment by tomalec** [comment]
I agree with @miyconst we should keep it in the same organization where Launcher is, as it is Launcher specific thing.
I have separated it from Launcher to make it easier to load bower dependencies, and to overwrite existing starcounter-include.

**Comment by warpech** [comment]
Then maybe it is enough to write this as the first line in the README.md:

> This is not a sample app. For the sample app, see [Launcher](https://github.com/StarcounterSamples/Launcher).

**Comment by warpech** [comment]
I will move it to StarcounterPrefabs. This is where Launcher is now.
